language: python
python:
- '2.7'
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
- sudo pip install -U docker-compose
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- docker exec docker_sfmwebharvester_1 python -m unittest discover
install: pip install -r requirements/requirements.txt
script: python -m unittest discover
notifications:
  email:
  - justinlittman@gmail.com
