FROM gwul/sfm-base@sha256:74fbacb81df7bb26f3efb67074b4b3fc2447bfd876d7197f932d08386cc068d0
MAINTAINER Justin Littman <justinlittman@gwu.edu>

ADD . /opt/sfm-web-harvester/
WORKDIR /opt/sfm-web-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

CMD sh /opt/sfm-setup/setup_reqs.sh \
    && appdeps.py --wait-secs 60 --port-wait mq:5672 --port-wait heritrix:8443 \
    && python web_harvester.py --debug=$DEBUG service mq $RABBITMQ_USER $RABBITMQ_PASSWORD https://heritrix:8443 $HERITRIX_USER $HERITRIX_PASSWORD $HERITRIX_CONTACT_URL /sfm-data/containers/$HOSTNAME
