FROM gwul/sfm-base@sha256:9ba2b7d757cf1a285e9af6fbcc35916155779f2944d3018247176a29e0904973
MAINTAINER Justin Littman <justinlittman@gwu.edu>

ADD . /opt/sfm-web-harvester/
WORKDIR /opt/sfm-web-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

CMD sh /opt/sfm-setup/setup_reqs.sh \
    && appdeps.py --wait-secs 60 --port-wait mq:5672 --port-wait heritrix:8443 --file-wait /sfm-data/collection_set --file-wait /sfm-data/containers \
    && gosu sfm python web_harvester.py --debug=$DEBUG service mq $RABBITMQ_USER $RABBITMQ_PASSWORD https://heritrix:8443 $HERITRIX_USER $HERITRIX_PASSWORD $HERITRIX_CONTACT_URL /sfm-data/containers/$HOSTNAME
