sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbitMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmheritrix:
    image: gwul/sfm-heritrix:master
    build: heritrix
    ports:
        - "8443:8443"
    environment:
        - HERITRIX_USER=sfm_user
        - HERITRIX_PASSWORD=password
    volumes_from:
        - sfmdata
sfmwebharvester:
    image: gwul/sfm-web-harvester:dev
    links:
        - sfmrabbit:mq
        - sfmheritrix:heritrix
    volumes:
        - "..:/opt/sfm-web-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
    environment:
        - DEBUG=True
        - HERITRIX_CONTACT_URL=http://myinstitution.edu
    volumes_from:
        - sfmdata
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
        - /sfm-data
